### PR TITLE
Games dev

### PR DESCRIPTION
**Pull request by tippi-fifestarr**

### CODE REVIEW

**Comment by tippi-fifestarr** [comment]
@alank101 @EmanHerawy @GigaHierz can you confirm / check that changes to app.ts and mongo are non-breaking and merge this?

**Comment by EmanHerawy** [comment]
Hi @tippi-fifestarr 
I know it was merged but this PR has the following issues :
1-  /submit accept submitting the same nft multiple time 
2- /voteForSubmission doesn't update the votes counts 
3- /mostLikedSubmission should be filtered by weektimstamp 

I haven't checked the other cycle related to characters because  I don't know the logic related to them in depth

**Comment by tippi-fifestarr** [comment]
1. Probably, yes. 
2. It did update when I tested it.  I checked the mongo, nobody else submitted anything?
3. we don't even have a weektimestamp in the submission, is this something you need for the Functions?

@EmanHerawy would any of these issues be a problem for this hackathon?  Can we save these schema changes until this weekend after we have the rest of the functionality in place?  

@alank101 is our backend guy so maybe he can look at this

**Comment by EmanHerawy** [comment]
> 3\. we don't even have a weektimestamp in the submission, is this something you need for the Functions?

yes, that's why in the  backend api version it was there , how can we get the winning nft per week? 

> 2\.It did update when I tested it. I checked the mongo, nobody else submitted anything?
I did tested it , the number of submission increased for the same token id 
`[
    {
        "_id": "6572ffa16c54eb6828e3c4db",
        "addressOfCreator": "example_wallet_address",
        "image": "base64_encoded_image_data",
        "likesAmount": 0,
        "tokenID": "61ed7dbd5e74cd134c0d5f3a",
        "chainId": 1,
        "voterWallets": []
    },
    {
        "_id": "657301566c54eb6828e3c4dc",
        "addressOfCreator": "example_wallet_address",
        "image": "base64_encoded_image_data",
        "likesAmount": 0,
        "tokenID": "61ed7dbd5e74cd134c0d5f3a",
        "chainId": 1,
        "voterWallets": []
    },
    {
        "_id": "657301586c54eb6828e3c4dd",
        "addressOfCreator": "example_wallet_address",
        "image": "base64_encoded_image_data",
        "likesAmount": 0,
        "tokenID": "61ed7dbd5e74cd134c0d5f3a",
        "chainId": 1,
        "voterWallets": []
    },
    {
        "_id": "6573015a6c54eb6828e3c4de",
        "addressOfCreator": "example_wallet_address",
        "image": "base64_encoded_image_data",
        "likesAmount": 0,
        "tokenID": "61ed7dbd5e74cd134c0d5f3a",
        "chainId": 1,
        "voterWallets": []
    },
    {
        "_id": "6573015b6c54eb6828e3c4df",
        "addressOfCreator": "example_wallet_address",
        "image": "base64_encoded_image_data",
        "likesAmount": 0,
        "tokenID": "61ed7dbd5e74cd134c0d5f3a",
        "chainId": 1,
        "voterWallets": []
    },
    {
        "_id": "6573107d6ef25892287b9caf",
        "addressOfCreator": "example_wallet_address",
        "image": "base64_encoded_image_data",
        "likesAmount": 0,
        "tokenID": "61ed7dbd5e74cd134c0d5f3a",
        "chainId": 1,
        "voterWallets": []
    },
    {
        "_id": "6573108d6ef25892287b9cb0",
        "addressOfCreator": "example_wallet_address",
        "image": "base64_encoded_image_data",
        "likesAmount": 0,
        "tokenID": "61ed7dbd5e74cd134c0d5f3a",
        "chainId": 1,
        "voterWallets": []
    }
]`

` would any of these issues be a problem for this hackathon? Can we save these schema changes until this weekend after we have the rest of the functionality in place?`

the third one, break the logic that we are mainly depending on, I need to update votes, and get the most voted one per week

**Pull request merged**
